import numpy as np
import os
from .precessing_surrogate import PrecessingSurrogate


def print_time(start, end, tag):
    print(f"{tag} time: {(end - start) * 1000:.2f} ms")


##############################################################################
class HybridSurrogate(PrecessingSurrogate):
    """
    A wrapper class for the precessing hybridized surrogate models.

    See the __call__ method on how to evaluate waveforms.
    """

    def __init__(self, nrsur):
        """
        Loads the surrogate model data.

        Arguments:
            nrsur: NRSurrogate object that can be used to call the NR-only surrogate
                   model. This is generated by gwsurrogate.LoadNRSurrogate(model_name).
                   At the moment, only tested for model_name='NRSur7dq8'.
        """

        self.nrsur = nrsur
        self.nrsur_dyn = nrsur._sur_dimless.dynamics_sur
        self.ellMax_model = nrsur._sur_dimless.ellMax_model
        self.debug = True  # FIXME
        self.make_plot = False

        if self.debug:
            # Only import the plotting functions if debug is True
            # That way, no unnecessary matplotlib imports are made.
            from .hyb_plot_utils import plot_hyb

            self.plot_hyb = plot_hyb

        # It's better to import here, so that the Julia session is not started
        # unless this class is used.
        from .pn_utils import generate_pn

        self.generate_pn = generate_pn
        # Do a dummy call to generate_pn so the Julia session is started and any
        # precompile steps are done.
        self.generate_pn(
            1.1,  # q
            [0.1, 0.2, 0.3],  # chiA0
            [0.3, 0.2, 0.1],  # chiB0
            1e-2,  # omega_ref
            9.5e-3,  # omega_start
            1.5e-2,  # omega_end
            -1000,  # t_ref
            1.239,  # dt
        )

    def get_dynamics(self):
        """Not implemented for HybridSurrogate."""
        raise NotImplementedError(
            "get_dynamics() is not implemented for HybridSurrogate."
        )

    # ------------------------------------------------------------------------
    def roll_on_function(self, t_MatchRegion, rollType="sinsq"):
        """Goes from 0 to 1 over t_MatchRegion"""

        t_min = t_MatchRegion[0]
        t_max = t_MatchRegion[-1]
        t = t_MatchRegion
        if rollType == "linear":
            rollOn = (t - t_min) / (t_max - t_min)
        elif rollType == "sinsq":
            rollOn = np.sin(np.pi / 2.0 * (t - t_min) / (t_max - t_min)) ** 2
        else:
            raise Exception("Unknown rollType")

        if abs(rollOn[0] - 0) > 1e-12 or abs(rollOn[-1] - 1) > 1e-12:
            raise Exception("rollOn has wrong values at ends.")

        return rollOn

    # ------------------------------------------------------------------------
    def stitch_nrsur_PN(
        self,
        t_nrsur,
        h_nrsur,
        chiA_nrsur,
        chiB_nrsur,
        orbphase_nrsur,
        t_pn,
        h_pn,
        chiA_pn,
        chiB_pn,
        idxStart_nrsur,
        n_orbits=3,
        plot_settings=None,
    ):
        # Get stitching window: n_orbits of the the NR waveform, starting from
        # t_nrsur[idxStart_nrsur].
        idxEnd_nrsur = np.argmin(
            np.abs(
                orbphase_nrsur
                - (orbphase_nrsur[idxStart_nrsur] + 2 * np.pi * n_orbits)
            )
        )

        if (
            abs(
                orbphase_nrsur[idxEnd_nrsur]
                - orbphase_nrsur[idxStart_nrsur]
                - 2 * np.pi * n_orbits
            )
            > np.pi / 10
        ):
            raise Exception(f"Expected window to be {n_orbits} long.")

        dt_nrsur = t_nrsur[1] - t_nrsur[0]
        if not np.allclose(np.diff(t_nrsur), dt_nrsur):
            raise Exception("Expected nrsur data to be uniform.")

        dt_pn = t_pn[1] - t_pn[0]
        if not np.allclose(np.diff(t_pn), dt_pn):
            raise Exception("Expected PN data to be uniform.")

        if abs(dt_nrsur - dt_pn) > 1e-6:
            raise Exception(
                f"Expected nrsur and PN time steps to match. "
                f"Got dt_nrsur={dt_nrsur} and dt_pn={dt_pn}."
            )

        if t_pn[0] > t_nrsur[0]:
            raise Exception(
                f"PN data (t_start={t_pn[0]}) is shorter than nrsur data (t_start={t_nrsur[0]})."
            )

        if t_nrsur[idxStart_nrsur] > t_nrsur[idxEnd_nrsur]:
            raise Exception("nrsur start time is later than the end time!")

        tWindow = t_nrsur[idxEnd_nrsur] - t_nrsur[idxStart_nrsur]

        # nrsur and PN are assumed to have been time shifted so that at
        # t=t_nrsur[idxStart_nrsur], they have the same frequency.
        tAlign_hyb = t_nrsur[idxStart_nrsur]
        idxStart_pn = np.argmin(np.abs(t_pn - tAlign_hyb))
        if t_pn[-1] < t_pn[idxStart_pn] + tWindow:
            raise Exception("PN data does not span the full window.")
        idxEnd_pn = np.argmin(np.abs(t_pn - (t_pn[idxStart_pn] + tWindow)))

        if abs(t_pn[idxStart_pn] - t_nrsur[idxStart_nrsur]) > 1e-5:
            raise Exception(
                f"Expected nrsur and PN start times to match. "
                f"Got t_pn={t_pn[idxStart_pn]} and "
                f"t_nrsur={t_nrsur[idxStart_nrsur]}."
            )

        if abs(t_pn[idxEnd_pn] - t_nrsur[idxEnd_nrsur]) > 1e-5:
            raise Exception(
                "Expected nrsur and PN end times to match. "
                f"Got t_pn={t_pn[idxEnd_pn]} and "
                f"t_nrsur={t_nrsur[idxEnd_nrsur]}."
            )

        if not np.allclose(
            t_pn[idxStart_pn:idxEnd_pn], t_nrsur[idxStart_nrsur:idxEnd_nrsur]
        ):
            raise Exception(
                "Expected nrsur and PN arrays within the window to match."
            )

        # FIXME uncomment
        # if np.linalg.norm(qcopr_pn.T[idxStart_pn] - np.array([1, 0, 0, 0])) > 1e-6:
        #    raise Exception("Expected identity quaternion at idxStart_pn")

        # time array for hybrid data, keeping in mind that nrsur and PN times match
        # exactly in the window.
        t_preWindow = t_pn[:idxStart_pn]
        t_inWindow = t_pn[idxStart_pn:idxEnd_pn]
        t_postWindow = t_nrsur[idxEnd_nrsur:]
        t_hyb = np.concatenate((t_preWindow, t_inWindow, t_postWindow))

        dt_hyb = t_hyb[1] - t_hyb[0]
        if not np.allclose(np.diff(t_hyb), dt_hyb, atol=1e-5):
            print(np.min(np.diff(t_hyb)), np.max(np.diff(t_hyb)))
            raise Exception("Expected hyb data to be uniform.")

        if not np.all(np.diff(t_hyb) > 0):
            raise Exception("Non monotonic time array.")

        def stitch_data(data_pn, data_nrsur):
            data_pn_preWindow = data_pn[:idxStart_pn]
            data_pn_inWindow = data_pn[idxStart_pn:idxEnd_pn]
            data_nrsur_inWindow = data_nrsur[idxStart_nrsur:idxEnd_nrsur]
            data_nrsur_postWindow = data_nrsur[idxEnd_nrsur:]
            data_hyb = np.concatenate(
                (
                    data_pn_preWindow,
                    data_pn_inWindow * (1 - rollOn)
                    + data_nrsur_inWindow * rollOn,
                    data_nrsur_postWindow,
                )
            )
            return data_hyb

        ## Stitch PN and nrsur data to get hybrid data
        rollOn = self.roll_on_function(t_inWindow)

        # Stitch waveform mode by mode
        h_hyb = {}
        for key in h_pn:
            h_hyb[key] = stitch_data(h_pn[key], h_nrsur[key])

        # Stich spins component by component
        chiA_hyb = []
        chiB_hyb = []
        for idx in range(3):
            chiA_hyb.append(stitch_data(chiA_pn.T[idx], chiA_nrsur.T[idx]))
            chiB_hyb.append(stitch_data(chiB_pn.T[idx], chiB_nrsur.T[idx]))
        chiA_hyb = np.array(chiA_hyb).T
        chiB_hyb = np.array(chiB_hyb).T

        if self.debug and self.make_plot:
            print(f"\nPlotting hybrid surrogate in {plot_settings['plot_dir']}")
            self.plot_hyb(
                t_pn,
                h_pn,
                t_nrsur,
                h_nrsur,
                t_hyb,
                h_hyb,
                idxStart_nrsur,
                idxEnd_nrsur,
                plot_settings["plot_dir"],
                chiA_pn,
                chiB_pn,
                chiA_nrsur,
                chiB_nrsur,
                chiA_hyb,
                chiB_hyb,
                plot_settings["title_tag"],
                plot_settings["plot_fname_prefix"],
            )

        return t_hyb, h_hyb, chiA_hyb, chiB_hyb

    def __call__(
        self,
        x,
        fM_low=None,
        fM_ref=None,
        tM_ref=None,
        dtM=None,
        timesM=None,
        dfM=None,
        freqsM=None,
        mode_list=None,
        ellMax=None,
        precessing_opts=None,
        tidal_opts=None,
        par_dict=None,
    ):
        """
        Evaluates a precessing surrogate model.

        Arguments:
            x:  Parameters, x = q, chiA0, chiB0. Where,
                q: The mass ratio mA/mB, where A (B) refers to the heavier BH.
                chiA0, chiB0:  The initial dimensionless spins given in the
                        coprecessing frame. They should be length 3 lists or numpy
                        arrays.  These are $\\vec{\chi_{1,2}^\mathrm{copr}(t_0)$ in
                        THE PAPER.

                chiA0: The chiA vector at the reference time.
                chiB0: The chiB vector at the reference time.
                The above spins use lalsimulation conventions, where
                    \chi_z = \chi \cdot \hat{L}, where L is the orbital angular
                        momentum vector at the epoch.
                    \chi_x = \chi \cdot \hat{n}, where n = body2 -> body1 is the
                        separation vector at the epoch. body1 is the heavier body.
                    \chi_y = \chi \cdot \hat{L \cross n}.
                    These spin components are frame-independent as they are
                    defined using vector inner products. This is equivalent to
                    specifying the spins in the coorbital frame used in the
                    surrogate papers.

            fM_low:     Initial frequency in dimensionless units. If fM_low = 0, the
                        full surrogate is returned.
            fM_ref:     Reference frequency in dimensionless units, at which the
                        reference frame and spins are defined.
            dtM:        Time step in dimensionless units.
            timesM:     Dimensionless times at which the output should be sampled.
                        Give at most one of dtM and timesM. If neither is given
                        returns the results sampled at self.t_coorb.
            dfM, freqsM: These should be None, as we only have time domain models so
                        far.
            mode_list:  This should be None, use ellMax instead.
            ellMax:     The maximum ell modes to use. The NRSur7dq4 surrogate model
                        contains modes up to L=4. Using ellMax=2 or ellMax=3 reduces
                        the evaluation time.

            precessing_opts:
                        A dictionary containing optional parameters for a precessing
                        surrogate model. Default: None.
                        Allowed keys are:
                        init_orbphase: The orbital phase in the coprecessing frame
                            at the reference epoch.
                            Default: None, in which case the coorbital frame and
                            coprecessing frame are the same.
                        init_quat: The unit quaternion (length 4 vector) giving the
                            rotation from the coprecessing frame to the inertial frame
                            at the reference epoch.
                            Default: None, in which case the coprecessing frame is the
                            same as the inertial frame.
                        return_dynamics:
                            Return the frame dynamics and spin evolution along with
                            the waveform. Default: False.
                        Example: precessing_opts = {
                                            'init_orbphase': 0,
                                            'init_quat': [1,0,0,0],
                                            'return_dynamics': True
                                            }
            tidal_opts: Should be None for this model.
            par_dict: A dictionary containing optional parameters for the
                      precessing surrogate model. Default: None.
                      Allowed keys are:
                      skip_m0_modes: If True, skip the m=0 modes in the coorbital frame.
                                     Default: False.


        Returns:
            domain, h, dynamics.
        """

        if self.debug:
            from time import time

            overall_start = time()

        # Get binary parameters
        q, chiA0, chiB0 = x

        if dfM is not None:
            raise ValueError("Expected dfM to be None for a Time domain model")
        if freqsM is not None:
            raise ValueError(
                "Expected freqsM to be None for a Time domain model"
            )
        if dtM is None:
            raise ValueError("dtM must be specified for hybrid surrogate.")
        if timesM is not None:
            raise ValueError(
                "timesM should not be specified for hybrid surrogate. Use dtM instead."
            )

        if precessing_opts is None:
            precessing_opts = {}
        if par_dict is None:
            par_dict = {}

        # Only allowed key for par_dict is skip_m0_modes, which defaults to True.   #FIXME
        skip_m0_modes = par_dict.pop("skip_m0_modes", True)
        self._check_unused_opts(par_dict, "par_dict")

        return_dynamics = precessing_opts.pop("return_dynamics", False)
        self._check_unused_opts(precessing_opts, "precessing_opts")

        if ellMax is None:
            ellMax = self.ellMax_model
        if ellMax > self.ellMax_model:
            raise ValueError(f"Model only allows ellMax<={self.ellMax_model}")

        # # The reference time is always the start of the NR surrogate.
        # if fM_ref is not None:
        #     raise ValueError(
        #         "fM_ref must be None for hybrid surrogate. "
        #     )

        # Get dimensionless omega_low
        if fM_low is None or fM_low == 0:
            raise ValueError(
                "fM_low must be specified and non-zero for hybrid surrogate."
            )
        omega_low_pn = fM_low * np.pi

        if self.debug:
            starttime_nrsur = time()

        # Evaluate the NR-only surrogate model
        t_nrsur, h_nrsur, dyn_nrsur = self.nrsur(
            q,
            chiA0,
            chiB0,
            f_low=0,  # We want the full length of the NR surrogate
            dt=dtM,
            ellMax=ellMax,
            precessing_opts={
                "return_dynamics": True,
            },
            par_dict={
                "skip_m0_modes": skip_m0_modes,  # Skip m=0 modes in the coorbital frame if True
            },
        )

        if self.debug:
            endtime_nrsur = time()
            print_time(starttime_nrsur, endtime_nrsur, "NRSur")

        # Get the dynamics from the NR surrogate
        orbphase_nrsur = dyn_nrsur["orbphase"]
        chiA_nrsur = dyn_nrsur["chiA"]
        chiB_nrsur = dyn_nrsur["chiB"]
        qcopr_nrsur = dyn_nrsur["q_copr"]

        # Get initial omega. Here we assume initial quat is unity and
        # initial orbphase is zero.
        # NOTE: This won't work if the reference time is not the start of the NR surrogate.
        y0 = np.append(
            np.array([1.0, 0.0, 0.0, 0.0, 0]), np.append(chiA0, chiB0)
        )
        omega0_nrsur = self.nrsur_dyn.get_time_deriv_from_index(
            0, q, y0, only_omega=True
        )

        # Start hybridization at the start of the surrogate data
        idxStart_nrsur = 0
        # Set PN t_ref to the start of the NR surrogate
        tref_for_pn = t_nrsur[idxStart_nrsur]

        if omega0_nrsur < omega_low_pn:
            raise ValueError(
                f"Initial omega_low_pn={omega_low_pn} must be less than "
                f"the initial omega of the NR surrogate {omega0_nrsur}."
            )

        if self.debug:
            starttime_pn = time()

        # NOTE: drop_memory_terms=True m=0 modes in the PN coorbital frame
        # gets dropped, and any other memory contributions to the other modes
        # are dropped as well. This is what we want when working with NR
        # surrogate without memory.
        t_pn, h_pn, chiA_pn, chiB_pn = self.generate_pn(
            q,
            chiA0,
            chiB0,
            omega0_nrsur,  # Reference frequency for PN (inertial frame=coorbital frame here and spins are input here in the same frame)
            omega_low_pn,  # Earliest frequency for backwards PN evolution
            omega0_nrsur
            * 1.1,  # End frequency for forwards PN evolution (we don't need to go too far, just need 3 orbits)    #FIXME, be smarter
            tref_for_pn,
            dtM,
            ellMax=ellMax,
            drop_memory_terms=skip_m0_modes,
            debug=self.debug,
        )
        if self.debug:
            endtime_pn = time()
            print_time(starttime_pn, endtime_pn, "PN")

        if self.debug:
            plot_dir = "HybPlots"
            plot_fname_prefix = "HybSur"
            if not os.path.exists(plot_dir):
                os.makedirs(plot_dir)

            # Title tag for plots
            chiA_tag = "$\\chi_A$=["
            chiB_tag = "$\\chi_B$=["
            for idx in range(3):
                chiA_tag += f"{chiA0[idx]:.2f}"
                chiB_tag += f"{chiB0[idx]:.2f}"
                if idx == 2:
                    chiA_tag += "]"
                    chiB_tag += "]"
                else:
                    chiA_tag += ", "
                    chiB_tag += ", "
            title_tag = (
                f"$q={q:.2f}$ {chiA_tag} {chiB_tag} at t={tref_for_pn:.2f}"
            )

            plot_settings = {
                "plot_dir": plot_dir,
                "plot_fname_prefix": plot_fname_prefix,
                "title_tag": title_tag,
            }
        else:
            plot_settings = None

        if self.debug:
            starttime_hyb = time()

        # Do the hybridization.
        t_hyb, h_hyb, chiA_hyb, chiB_hyb = self.stitch_nrsur_PN(
            t_nrsur,
            h_nrsur,
            chiA_nrsur,
            chiB_nrsur,
            orbphase_nrsur,
            t_pn,
            h_pn,
            chiA_pn,
            chiB_pn,
            idxStart_nrsur,
            plot_settings=plot_settings,
        )

        if self.debug:
            endtime_hyb = time()
            print_time(starttime_hyb, endtime_hyb, "Hyb")

        dynamics = {
            "chiA": chiA_hyb,
            "chiB": chiB_hyb,
            # "q_copr": quat,
            # "orbphase": orbphase,
        }

        if self.debug:
            overall_end = time()
            print_time(overall_start, overall_end, "Full")

        return t_hyb, h_hyb, dynamics
